### ISSUE TITLE
Layouts are missing - Fixed

### ISSUE THREAD

**Issue by rgleason** [rgleason/LogbookKonni_pi#13]
Shouldn't layouts be kept in the GetPrivateApplicationDataLocation()?  which allows user changes.
I don't use this plugin regularly but aren't user changes allowed to the layouts and alternative layouts permitted? 

If this is correct, then we should (in code)
1. Expand layouts.zip  located in the normal data/ directory into the GetPrivateApplicationDataLocation()
2. Make sure these layouts are then "found" when running the program.
3. Remove the expanded 3 layout subdirectories from the normal /data/ directory, leaving Layouts.zip..

I would appreciate some code assistance to do Item #1 above.

**Comment by rgleason** [comment]
Have tried in Windows10 this:

Copy Clouds,  HTMLLayouts and ODTLayouts  

from  C:\Users\Rick\AppData\Local\opencpn\plugins\logbookkonni_pi\data
which is derived from GetPluginDataDir

to   C:\ProgramData\opencpn\plugins\logbookdata
which is derived from GetPrivateApplicationDataLocation

Is "logbookdata"  the correct name?  I don't think so. Needs fixxing.

Now we have Layouts available!

![Screenshot (199)](https://user-images.githubusercontent.com/2363959/117022673-6b61b680-acc6-11eb-911d-9c58591d5b14.png)

So we just need the code and dependencies for unzipping from one location to another so the user does not have to copy these directories, and we need to find the right initialization area to put this action.

NOTE: Also moved Layouts.zip up out of Layouts dir into the data/ directory and deleted Layouts directory.

**Comment by filochard** [comment]
Hi Rick
You did a huge job
I don't know for Windows installation ...
but inside flatpak
there are two different path for the data  (same scheme as with weatherfax)

- 1 for the plugin itself (readonly) : 
/home/yourusername/.var/app/org.opencpn.OpenCPN/data/opencpn/plugins/logbookkonni_pi/data/

-  2 for the user (writeable) where he may find modifiable layouts (in their subirectories HTMLLayouts ODTLayout CLOUDS ) and store the  .txt files : 
/home/yourusername/.var/app/org.opencpn.OpenCPN/config/opencpn/plugins/logbook/

NB there is no /data/ subdirectory in this second path 
NB bis : in Linux the conventional name inside this second path is logbook and not logbookkonni

**Comment by filochard** [comment]
In the delatlabel version the install button did the job of 
showing the tree where to look for the zip file 
letting you find and select it
and then unzipping in the right place

**Comment by rgleason** [comment]
Now deploying 
https://cloudsmith.io/~opencpn/repos/logbookkonni-alpha/packages/

**Comment by rgleason** [comment]
Here are the main functions and procedures that weather_routing uses to copy user changeable files from getPluginDataDir  locations to GetpPrivateApplicationDataLocation() that are user writable.

[weather_routing-User-Data-Handling.txt](https://github.com/rgleason/LogbookKonni_pi/files/6424490/weather_routing-User-Data-Handling.txt)

**Comment by rgleason** [comment]
I believe the location where the above changes should probably occur is 

**Logbook_pi.cpp  Starting Line 1430** 

```
void logbookkonni_pi::loadLayouts( wxWindow *parent )
{
    wxString FILE = _T( "LogbookKonni*.zip" );
    std::auto_ptr<wxZipEntry> entry;
    wxString path, sep;
    sep = wxFileName::GetPathSeparator();

    wxString data = StandardPath();
    data.Append( _T( "data" ) );
    data.append( sep );
    if ( !wxDir::Exists( data ) )
        wxMkdir( data );

    wxString data1 = data;
    wxString data2 = data;
    wxString data3 = data;
    wxString help  = data;

    data.Append( _T( "HTMLLayouts" ) );
    data.append( sep );
    if ( !wxDir::Exists( data ) )
        wxMkdir( data );

    data1.Append( _T( "ODTLayouts" ) );
    data1.append( sep );
    if ( !wxDir::Exists( data1 ) )
        wxMkdir( data1 );

    data2.Append( _T( "Clouds" ) );
    data2.append( sep );
    if ( !wxDir::Exists( data2 ) )
        wxMkdir( data2 );

```

**Comment by filochard** [comment]
Hi Rick
In the txt file https://github.com/rgleason/LogbookKonni_pi/files/6424490/weather_routing-User-Data-Handling.txt
I saw this : 
(in the line 68 of your txt file)

LINE 133
{
    wxFileConfig *pConf = GetOCPNConfigObject();
    pConf->SetPath ( _T( "/PlugIns/WeatherRouting" ) );
    
and that (in the line 150 of your txt file
LINE 212		
		else if (result[i] == 1) {
            wxString cfg = GetPluginDataDir("weather_routing_pi") + _T("/data/") + _T("WeatherRoutingConfiguration.xml");
		    if (wxFileName::FileExists(cfg))
			wxCopyFile(cfg, m_default_configuration_path);
		}
            }
            pConf->SetPath ( _T( "/PlugIns/WeatherRouting" ) ); // path can change after modal dialog
            pConf->Write (  _T ( "ConfigVersion" ), PLUGIN_VERSION_MAJOR * 100 + PLUGIN_VERSION_MINOR);
        }

This refers to /PlugIns/WeatherRouting     and there it is written PlugIns  not Plugins
which is different from /plugins/weatherrouting_pi

and else
in line 45 to 48 from your txt file
	Line 167:         CopyDataFiles(GetPluginDataDir("weather_routing_pi") + _T("/data/boats"), boatsdir);
	Line 169:         CopyDataFiles(GetPluginDataDir("weather_routing_pi") + _T("/data/polars"), polarsdir);
	Line 208:                 CopyDataFiles(GetPluginDataDir("weather_routing_pi") + _T("/data/boats"), boatsdir);
	Line 209:                 CopyDataFiles(GetPluginDataDir("weather_routing_pi") + _T("/data/polars"), polarsdir);

the targets to copy the data are boatsdir and polarsdir (these seem to be the users-specific directory) 
Where are those boatsdir and polarsdir  explicitly defined ?

**Comment by rgleason** [comment]
I see this error, "plugIns" oddly it hasn't shown itself to me, but should be fixed
WEATHERROUTING.CPP    LINE 133
```
{
    wxFileConfig *pConf = GetOCPNConfigObject();
    pConf->SetPath ( _T( "/PlugIns/WeatherRouting" ) );
```
 Thank you.

notepad++  "Find in files" on boatdir

```
Search "boatsdir" (5 hits in 1 file of 27 searched)
  C:\Users\Rick\Documents\GitHub\weather_routing_pi\src\WeatherRouting.cpp (5 hits)
	Line 152:     wxString boatsdir = weather_routing_pi::StandardPath() + wxFileName::GetPathSeparator() + _T("boats");
	Line 153:     if (!wxFileName::DirExists(boatsdir))
	Line 162:     fn.Mkdir(boatsdir);
	Line 167:         CopyDataFiles(GetPluginDataDir("weather_routing_pi") + _T("/data/boats"), boatsdir);
	Line 208:                 CopyDataFiles(GetPluginDataDir("weather_routing_pi") + _T("/data/boats"), boatsdir);

```
Notepad++ "Find in files" on  polarsdir
Search "polarsdir" (5 hits in 1 file of 27 searched)
  C:\Users\Rick\Documents\GitHub\weather_routing_pi\src\WeatherRouting.cpp (5 hits)
	Line 155:     wxString polarsdir = weather_routing_pi::StandardPath() + wxFileName::GetPathSeparator() + _T("polars");
	Line 156:     if (!wxFileName::DirExists(polarsdir))
	Line 163:     fn.Mkdir(polarsdir);
	Line 169:         CopyDataFiles(GetPluginDataDir("weather_routing_pi") + _T("/data/polars"), polarsdir);
	Line 209:                 CopyDataFiles(GetPluginDataDir("weather_routing_pi") + _T("/data/polars"), polarsdir);

**Comment by filochard** [comment]
Hi Rick
I just corrected an erratum in this comment editing it: 
https://github.com/rgleason/LogbookKonni_pi/issues/13?_pjax=%23js-repo-pjax-container#issuecomment-832022762

I forgot the mention the data subdirectory where are copied the subdirecories HTMLLayouts ODTLayouts Clouds and where are created the *.txt files

 The three last lines of the comment are now : 
    /home/yourusername/.var/app/org.opencpn.OpenCPN/config/opencpn/plugins/logbook/data

NB : in Linux there's a data subdirectory in this second pah (it's different from weatherfax or weather_routing )
NB bis : in Linux the conventional name inside this second path is logbook and not logbookkonni

**Comment by rgleason** [comment]
@filochard   I've cleaned things up a little updated FE2 and pushed a new version v1.4.13.30 to CS
 https://cloudsmith.io/~opencpn/repos/logbookkonni-alpha/packages/
if you would like to try it.  I have found logbook to be a big program with lots of code!
This version does fix the GetpPrivateApplicationDataLocation  issue so user is able to write to a user directory.

Re your note above..   Windows seems to have a  "logbookdata" directory, when it should be "logbook", but it works ok.  Also,I am not certain how all the mechanisms for various OS work, so right now I don't have much control over that part.   Key part is does it work properly.

Note: I  have not yet figured out how to unzip the 3 layout directories in layout.zip into the user data directory. So this will have to be done manually for the time being.   Then the layouts work properly.

**Comment by rgleason** [comment]
v1.4.13.31  commented out line 290
```
# Disables Logbook Install and Uninstall Preferences buttons.
#add_definitions("-DLAYOUTS_HACK")  

```
 and in "Preferences"  clicked on the Install Layouts button at the bottom and opened
%localappdata%\opencpn\plugins\logbookkonni_pi\data   OR
C:\Users\Rick\AppData\Local\opencpn\plugins\logbookkonni_pi\data
to select the layouts.zip file

and the files were unzipped and copied into automatically
C:\ProgramData\opencpn\plugins\logbookdata
 
![image](https://user-images.githubusercontent.com/2363959/117312845-61b98980-ae53-11eb-8234-fe6fb675ea95.png)

**Comment by rgleason** [comment]
Also I've added a missing datactrl file so perhaps Android will build, and I will next push this version up to Cloudsmith.

**Comment by rgleason** [comment]
from this branch https://github.com/rgleason/LogbookKonni_pi/tree/master-updateFE
It should be depolying int the "beta" directory now
https://cloudsmith.io/~opencpn/repos/logbookkonni-beta/packages/

got to go.

**Comment by filochard** [comment]
Hi Rick
You 're a genius !!!
Everything works now !
I downloaded and installed logbookonni_pi
Clicked the install button for the Layouts.zip :  it opens a window (kind of file manager) where to search the zippped file
I found it (because I know where to find it) and clicked on it
The HTMLLayout and the ODTLayout and the Clouds directories are created in : 
/home/myusername/.var/app/org.opencpn.OpenCPN/config/opencpn/plugins/logbookdata/

And here are stored the empty *.txt files that the installation  created 

When I modify one of the txt files, it is backedup  (for instance when I create a new logbook inside the plugin GUI  that creates a new logbook.txt besides a logbook.Bak)
I can export the logbook or the crewlist  or anything else with the layout I choose in .html or .odt format and save them in the directory I choose
Everything works as intended inside flatpak with its limits : 
- Some settings are not possible  : Inside flatpak we can't give logbookkonni a valid path to firefox or libreoffice or an html editor from the host system because these binaries are outside of the flatpak sandbox 
If we want to modify the provided layouts this must be done outside of flatpak 
-Because from flatpak we  cannot access to firefox (or any html viewer) we can't display the logbookkonni help...

NB : It would be useful to tell somewhere what is the path to the zip file (not so easy to find for a newbie) : 
/home/myusername/.var/app/org.opencpn.OpenCPN/data/opencpn/plugins/logbookkonni_pi/data/

PS : usually in linux the personal files are stored in a subdirectory : 
 .opencpn/plugins/logbook/data 
For flatpak  (and perhaps Windows) it appears to be : 
opencpn/plugins/logbookdata  
nevermind it works this way 
Nevertheless if you may modify this so that it is the same kind of path as it was for linux (and perhaps all the OS) : create a data subdirectory of logbook
 That would prevent "non flatpak users" from some problems  when updating with deb or rpm packages built on this code
They have the risk to no more find the files they created before this update

**Comment by rgleason** [comment]
Filochard   thank you for taking the time to test and report your findings.

I could modify the **Help.html  f**ile to give the various paths for different OS.

User writable Directory = Layouts unziped  HTMLLayout and the ODTLayout and the Clouds directories

**Windows**
Layouts.zip Directory -  C:\Users\<User>\AppData\Local\opencpn\plugins\logbookkonni_pi\data   OR  %localappdata%\opencpn\plugins\logbookkonni_pooi\data
User writable Directory - C:\ProgramData\opencpn\plugins\logbookdata

**Linux**
Layouts.zip Directory - /home/myusername/.var/app/org.opencpn.OpenCPN/data/opencpn/plugins/logbookkonni_pi/data/
User writable Directory -.opencpn/plugins/logbook/data

**Flatpak**
Layouts.zip Directory - ?
User writable Directory  - .opencpn/plugins/logbook/data

**MacOS**
Layouts.zip Directory -  ?
User writable Directory - ?

**Flatpak Help.**   Won't  Flatpak run Firefox?  Seems draconian.
Or Is there some way of being in a "Flatpak" window running on Ubuntu 20.04 for example, and alt-tabbing  out of OpenCPN into Ubuntu with Firefox running the Html file?  Users could make a separate link into the Help html file or just copy it out of flatpak to some location and put it on the desktop or something.  Flatpak sounds like it is a bit of a pain.

**_Future Layouts Installation_**
I would like to work on this plugin later to have automatic installation of s the layout files, however, there is the problem of overwriting user changes to the layouts.  Therefore this should be an option selected by the user, by use of a question during installation if there are no layout files found in the destination, then there would be a question, "Install Layouts directories and files? Yes, no.   Your thoughts would be appreciated.

**Update wxWidgets and wxFormBuilder**
Someday soon we are going to need to find a real programmer to update the basic code to use more modern wxWidgets commands. I believe whoever does this is going to have to be pretty skilled to keep all the features that Konni programmed.  He certainly put his heart into this fine piece of work and it shows, but we really need an update!  Many procedures are antiquated.

Once we confirm the paths I will add that to the html.

**Comment by filochard** [comment]
> 
> I could modify the **Help.html f**ile to give the various paths for different OS.
> 
> User writable Directory = Layouts unziped HTMLLayout and the ODTLayout and the Clouds directories
> 
> **Windows**
> Layouts.zip Directory - C:\Users<User>\AppData\Local\opencpn\plugins\logbookkonni_pi\data OR %localappdata%\opencpn\plugins\logbookkonni_pooi\data
> User writable Directory - C:\ProgramData\opencpn\plugins\logbookdata
> 
> **Linux**
> Layouts.zip Directory - /home/myusername/.var/app/org.opencpn.OpenCPN/data/opencpn/plugins/logbookkonni_pi/data/
> User writable Directory -.opencpn/plugins/logbook/data
> 
Indeed inside Linux (using the last delatbabel version1.4008) it was :  
Layouts.zip Directory = /usr/share/opencpn/plugins/logbookkonni_pi/data/
User writable Directory  = /home/myusername/.opencpn/plugins/**logbook/data/**

NB the path beginning with /usr/share...   is not a user path !!!  it's the place where are stored the binaries, libraries, locales, etc...
NB bis I've not yet tried to build a rpm with your last code and to update my last rpm (using the last delatbabel version1.4008)
I will try to verify if there is no problem since you seem to have modified the end of the path for the writeable directory from logbook/data to logbookdata

> **Flatpak**
> Layouts.zip Directory - ?
> User writable Directory - .opencpn/plugins/logbook/data
>
For Flatpak inside a Linux host system  (with your last 4.13.31 version)
Layouts.zip Directory = /home/myusername/.var/app/org.opencpn.OpenCPN/data/opencpn/plugins/logbookkonni_pi/data/
User writable Directory = /home/myusername/.var/app/org.opencpn.OpenCPN/config/opencpn/plugins/logbookdata/

I think it would be better to create a logbook/data subdirectory (same scheme as with delatbabel and konni) than a simple logbookdata directory  

> 
> **Flatpak Help.** Won't Flatpak run Firefox? Seems draconian.
> Or Is there some way of being in a "Flatpak" window running on Ubuntu 20.04 for example, and alt-tabbing out of OpenCPN into Ubuntu with Firefox running the Html file? Users could make a separate link into the Help html file or just copy it out of flatpak to some location and put it on the desktop or something. Flatpak sounds like it is a bit of a pain.
> 
It's a possible workaround to install inside a flatpak box other programs such as firefox and libreoffice for instance , this way logbookkonni would have access to the path to their binaries in its settings window

> **_Future Layouts Installation_**
> I would like to work on this plugin later to have automatic installation of s the layout files, however, there is the problem of overwriting user changes to the layouts. Therefore this should be an option selected by the user, by use of a question during installation if there are no layout files found in the destination, then there would be a question, "Install Layouts directories and files? Yes, no. Your thoughts would be appreciated.
> 
Indeed there is a huge problem that I didn't even think about since I only tried fresh install of flatpak opencpn ! I was really stupid suggesting to automatically install the layouts in the writeable directory : 
It's better to let the choice so that when you update you won't erase and overwrite your modified layouts and txt files

> PS: Will check the logbookdata path.

**Comment by rgleason** [comment]
filochard Thank you!  I made those path changes as you note in my post above.  I agree, maybe we need to put in a delimiter "/"  so  it is logbook/data.  That is the next thing that should be done. Perhaps tonight I will have time.

**Comment by filochard** [comment]
Ok
I just noticed a problem when using logbookkonni
It works

But as opencpn is launched from a console 
(flatpak run  org.opencpn.OpenCPN )
or in my particular case
(flatpak run --filesystem=/path-to-my-own-host-system-charts/ org.opencpn.OpenCPN )

In the console windows, I can see those gtk warnings messages when I use the logbook plugin : 
(opencpn:2): Gtk-CRITICAL **: 15:14:45.170: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar
repeated 4 times
(opencpn:2): Gtk-WARNING **: 15:14:45.170: Negative content width -9 (allocation 25, extents 17x17) while allocating gadget (node button, owner GtkButton)
repeated 4 times 
and then
(opencpn:2): Gtk-CRITICAL **: 15:14:45.170: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar
repeated again 3 times
(opencpn:2): Gtk-WARNING **: 15:14:45.170: Negative content width -9 (allocation 25, extents 17x17) while allocating gadget (node button, owner GtkButton)
repeated hundred times...
That doesn' prevent it to work

Out of topic : I built an rpm with the 1.4.13.31 tar.gz
installed it and installed the zip file
It creates then 
this User writable Directory = /home/myusername/.var/app/org.opencpn.OpenCPN/config/opencpn/plugins/logbookdata/
instead of a 
User writable Directory = /home/myusername/.var/app/org.opencpn.OpenCPN/config/opencpn/plugins/logbook/data/


But when I launch this plugin it segfaults ... without explanation 

when the 1.4008 version from delatbabel didn't

I will try later to explore the reason of this segfault (I have created a debug rpm...)

**Comment by rgleason** [comment]
Re the gtk-critical  I will have to ask Jon Gough. Will be back tonight.

**Comment by filochard** [comment]
Hi Rick
I think that the gtk warnings comes from the fact that the wxgtk version used to build the flatpak plugin is different from the wxgtk version of my system
That doesn't prevent it to work

**Comment by rgleason** [comment]
Thanks. Layouts is fixed. Now we have a path problem, that I have not been able to work out.
See
https://github.com/rgleason/LogbookKonni_pi/issues/19

**Comment by erwinlagu** [comment]
Thank You.
