### ISSUE TITLE
Flatpak  Logbook v1.4.14.0 will not install

### ISSUE THREAD

**Issue by rgleason** [rgleason/LogbookKonni_pi#25]
@filochard   Have you tried Logbook v1.4.14.0 in Flatpak?  What is your experience?

**Comment by filochard** [comment]
Hi 
I didn't know it was proposed
Just tried it
3 problems
1) it doesn't install the layouts (even if a message says it has installed them in the right path)
2) it doesn't store the txt file
3) we can't uninstall it to go to a previous version

The 1.3.13.31 was working (even if the config path ended with logbookdata instead of logbook/data)

**Comment by filochard** [comment]
There no button to install again or uninstall (as there are for other plugins in the tools/options/plugins menu)
only a preferences button
![screen_20210512-173913](https://user-images.githubusercontent.com/16304019/118003692-13bbee80-b349-11eb-8c79-102e203c0359.png)
![screen_20210512-173939](https://user-images.githubusercontent.com/16304019/118003753-22a2a100-b349-11eb-81e5-7703134b8d42.png)

**Comment by filochard** [comment]
I tried it but can't downgrade to the previous working alpha version 1.4.13.31

**Comment by rgleason** [comment]
So sorry,   Perhaps you can force it by using "Import Plugin " after downloading the older version from here
https://cloudsmith.io/~opencpn/repos/logbookkonni-beta/packages/?page=4

You can go back to 1.4.13.5  which is from the master-updateFE branch.

Tonight I am going to have to use this branch and try just adding the delimiter between logbook and data.
Then make a PR to master.

**Comment by filochard** [comment]
Hi
I stopped opencpn and started it again
The reinstall and uninstall buttons appeared ! 
So I could uninstall version 1.4.14.0 and went back to 1.4.13.31 that was the best working version : even if the config path is not canonical (ending in logbookdata instead of logbook/data ) it is found and useable

**Comment by rgleason** [comment]
Flatpak  v1.4.14.1 will not install either.  Is this because it is for bionic 18.08? and not 18.04?

**Comment by rgleason** [comment]
Thanks, closing. moving to https://github.com/rgleason/LogbookKonni_pi/issues/26
