### ISSUE TITLE
fix getpPrivateApplicationLocation

### ISSUE THREAD

**Issue by rgleason** [rgleason/LogbookKonni_pi#31]
@filochard wrote about logbook at bottom of post.
https://github.com/OpenCPN/OpenCPN/issues/2306#issuecomment-862492941

@leamas can you take a look I. thought I had fixed this and pushed up to PIM.

@filochard are you sure you are using the updated PIM version?

Perhaps I got something wrong.

**Comment by leamas** [comment]
@filochard: Which version are you using? What is the problem you see?

**Comment by filochard** [comment]
For watchdog I tried to update to 2.4.31.0 from the plugin manager
I get this
![screen_20210618-135207](https://user-images.githubusercontent.com/16304019/122557257-d7ad3500-d03c-11eb-8b76-b05a0545a3fc.png)
If I download it from : 
https://cloudsmith.io/~opencpn/repos/watchdog-prod/packages/
I can update to 2.4.31.0
no change : the xml file is stored in the wrong directory
/home/myusername/.opencpn/plugins/watchdog/
instead of 
/home/myusername/.var/app/org.opencpn.OpenCPN/config/opencpn/plugins/watchdog/

if I download it from
https://cloudsmith.io/~opencpn/repos/watchdog-beta/packages/
I can update to 2.4.31.1
then the xml file is always stored in a right place

Something wrong in the catalogue I think
And a wrong place for the tarball in the cloud

**Comment by leamas** [comment]
@rgleason: This is yours to handle...

**Comment by leamas** [comment]
I have tested 2..4.31 as built directly from source, and for me it worked just fine. So, as you say, this is most likely just some silly catalog issue (or rather build i. e., the build has not uploaded the tarball to the proper location). Let's leave this to Rick.

The open issue is about this plugin  LogBookKonni. You seem to have mentioned it at the and of your post as problematic. My initial questions "Which version" and "What's the problem" was actually about LogBookKonni...

**Comment by filochard** [comment]
Sorry I was not clear in the end of this comment : 
https://github.com/OpenCPN/OpenCPN/issues/2306#issuecomment-862492941
What I meant was that watchdog needed the same solution as what had been done to logbookkoni which works now (layouts installed in the right directory and txt files too)

**Comment by rgleason** [comment]
Good about logbook. Not to clear about what but I think alec fixed it.

1st sail this year back in 2-3 days and will update pim. Many thanks to @leamas @filochard

**Comment by leamas** [comment]
Don't mention me here -- I don't have a single commit in LogBook... Seems that you fixed it yourself
.

**Comment by rgleason** [comment]
Closing. Done
