### ISSUE TITLE
OpenCPN crashes with logbook plugin. 

### ISSUE THREAD

**Issue by mgrouch** [rgleason/LogbookKonni_pi#54]
See more details here:

https://github.com/OpenCPN/OpenCPN/issues/2567

**Comment by rgleason** [comment]
BTW, we no longer support Buster, so this should be closed I think.

**Comment by mgrouch** [comment]
Are you saying 5.6.0 is not supported on Buster? 
It’s has more issues on Bullseye than on Buster in my experience.

**Comment by leamas** [comment]
> BTW, we no longer support Buster, so this should be closed I think.

There is basically no "we" here, you are the maintainer and decision maker when it comes to supporting buster or not.

That said,  not supporting buster is pretty aggressive. I'm not aware of any other plugins which is only supported on Bullseye.

**Comment by leamas** [comment]
but you see 10 and 11 i. e., buster and bullseye

**Comment by rgleason** [comment]
Sorry, I guess I am not good at translation it says armhf and arm64 i believe but I get it now.

**Comment by leamas** [comment]
@mgrouch filed a new one, same bug: https://github.com/OpenCPN/OpenCPN/issues/2611

**Comment by rgleason** [comment]
@mgrouch  reports


```
ASSERT INFO:
/usr/include/wx-3.0/wx/arrstr.h(178): assert "nIndex < m_nCount" failed in Item(): wxArrayString: index out of bounds

BACKTRACE:
[1] logbookkonni_pi::LoadConfig()
[2] logbookkonni_pi::Init()
[3] PlugInManager::LoadPlugInDirectory(wxString const&, bool, bool)
[4] PlugInManager::LoadAllPlugIns(bool, bool)
[5] MyFrame::OnInitTimer(wxTimerEvent&)
[6] wxAppConsoleBase::CallEventHandler(wxEvtHandler*, wxEventFunctor&, wxEvent&) const
[7] wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&)
[8] wxEventHashTable::HandleEvent(wxEvent&, wxEvtHandler*)
[9] wxEvtHandler::TryHereOnly(wxEvent&)
[10] wxEvtHandler::ProcessEventLocally(wxEvent&)
[11] wxEvtHandler::ProcessEvent(wxEvent&)
[12] wxEvtHandler::SafelyProcessEvent(wxEvent&)
[13] wxTimerImpl::SendEvent()


```

I have absolutely no idea which of the OS is causing the problem?
and once I know, I will simple remove it, since I don't know how to fix it.

**Comment by filochard** [comment]
Hi Rick
I can bring my 2 pences : 
When I built rpm packages for linux I got crashes with logbookkonni and opencpn when both of them were built with wxgtku3.1-devel : 
I had to rebuild opencpn and all its plugins strictly with wxgtku3.0-devel and everything was OK then

I don't know which versions of wxgtku are used to build opencpn and logbookkonni for this OS but there's perhaps a conflict ...
Unless the source code is rewritten for wxgtku3.1 for opencpn and every plugin You must strictly build all of them upon wxgtku3.0

**Comment by rgleason** [comment]
Why would we drop it, when there are other OS where it works.

**Comment by leamas** [comment]
such as?

**Comment by filochard** [comment]
Hi Alec and Rick
about wxwidgets
In Linux (Mageia in my case) we can have wxgtku3.0 and wxgtku3.1.4 libraries side by side, this allows to use programs built on each of those versions.
When wxgtku3.1 appeared, all the programs provided by Mageia8 were rebuilt upon wxgtku3.1 when they were previously built upon wxgtku3.0 in Mageia7
For this reason I got strange segfaults because of logbookkonni
The most strange of the story was that a fresh install of Mageia8 and a first use of opencpn and its plugins built upon wxgtku3.1 caused segfaults
But updating a previous install of Mageia7 to Mageia8 (and so from opencpn and plugins built upon wxgtk3.0 to opencpn and plugins built upon wxgtk3.1) when the first install had been used I didn't get segfaults !!!!

The reason staid in the directory created by the first use of opencpn : 
if this /home/username/.opencpn had been created by opencpn built upon wxgtku3.0  and then used by the updated opencpn it was OK (from Mageia7 to Mageia8)
but if this /home/username/.opencpn had been created by a fresh install of Mageia8 and opencpn built upon wxgtku3.1  ... opencpn crashed
I spent days and hours to understand what was the culprit : logbookkonni creates something wrong in the user's conf  files when it has been built upon wxgtku3.1, 
but logbookkoni doesn't create bad files when it has been built with wxgtku3.0... and those files can be used later by opencpn and logbookkoni built upon wxgtku3.1 without causing segfaults !!!

This is the only plugin causing segfault when built with wxgtku3.1 and used after a fresh install (opencpn and all the other plugins built with wxgtku3.1 are OK)
That's the reason why I strictly built opencpn and its plugins upon wxgtku3.0 for the packages of Mageia8

I talked about this there https://github.com/OpenCPN/plugins/issues/578
adding links to an other program (guayadeque) having problems when it was rebuilt upon wxgtku3.1.4 although it was OK with wxgtku3.0
 https://github.com/OpenCPN/plugins/issues/578#issuecomment-1013261418
the developer of guayadeque modified the code to be compliant with wxgtku3.1.4
https://github.com/anonbeat/guayadeque/commit/24353c0e036ff592da67b7e1a18946e1ad858be4
and then later to wxgtku3.1.5
https://github.com/anonbeat/guayadeque/issues/138

**Comment by rgleason** [comment]
Phillipe, Thank you. That is very helpful. You are persistent.  
It appears to me that logbook, being an old plugin is using some depricated code which needs to be improved. 
I am going to link this to Logbook Issues.  There may be other plugins which have a similar problem.
https://github.com/rgleason/LogbookKonni_pi/issues/new

**Comment by rgleason** [comment]
@mgrouch  Is this fixed with the new version? If so, please close.
